### ISSUE TITLE
달력 로직 이슈

### ISSUE THREAD

**Issue by lhj12ps** [yellow-w/theGreatest6#86]
- 개별적으로 html+js로 달력 로직을 구현함.
- 프로젝트로 html과 js를 끌고오니 사이트에서 먹히지 않는 현상 발생 : 자고 일어나서 다시 볼 예정
- 이전달과 다음달은 넘어가나, 그 이상은 안 넘어가는 현상 발생
- 예) 3월이면 2월, 4월은 보이지만 나머지로는 이동이 안됨. : 자고 일어나서 다시 볼 예정

**Comment by yellow-w** [comment]
이슈 확인했습니다! 
올려주신 코드 확인 후 피드백 드리도록 하겠습니다.
고생많으셨어요 현진님!

**Comment by yellow-w** [comment]
현진님 작성해주신 코드 잘 보았습니다.
코드가 정말 깔끔하네요! 🥰👍🏻👍🏻

로직은 구현됬으나 화면에서 넘어가지 않는 것은
달력 그리는 부분이 지난달, 이번달, 다음달로 작성되어 있어서
3달만 보이는 것 같습니다...

아마 3달치에 대한 렌더 부분을 반복을 4회 돌리면 1년치가 될 것 같은데
자세한 건 마라톤 뛰고 와서 다시 한번 생각해보겠습니다...😃!!

**Comment by lhj12ps** [comment]
관련 이슈 해결했습니다!
